"""init all

Revision ID: 3d8e6accb4f0
Revises: 2b487158440c
Create Date: 2025-11-09 17:33:17.270965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8e6accb4f0'
down_revision = '2b487158440c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_panel_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('code_language', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('code_language')
        batch_op.drop_column('code_panel_enabled')

    # ### end Alembic commands ###
