"""init all

Revision ID: 7e0d10660a77
Revises: 3d8e6accb4f0
Create Date: 2025-11-10 16:11:53.460793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0d10660a77'
down_revision = '3d8e6accb4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_idx', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'section', ['section_id'], ['id'])

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_idx', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'section', ['section_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_idx')
        batch_op.drop_column('section_id')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_idx')
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###
